import Head from "next/head";
import ContentLayout from "../components/Layouts/ContentLayout";

import Styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="preload"
          href="/fonts/IranSansWeb/IRANSansWeb_Bold.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <ContentLayout />
    </div>
  );
}
